name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install ROS messages
      run: sudo apt install ros-geometry-msgs ros-visualization-msgs ros-sensor-msgs ros-nav-msgs ros-tf2-msgs ros-rosgraph-msgs
    - name: Build
      run: ROSRUST_MSG_PATH=/usr/share/ cargo build --verbose
    - name: Run tests
      run: ROSRUST_MSG_PATH=/usr/share/ cargo test --verbose
